name: BlockRegen
main: nl.aurorion.blockregen.BlockRegenPluginImpl
version: ${project.version}
authors: [ Aurorion, Wertik1206 ]
contributors: [ czmdav ]
softdepend:
  - Mutliverse-Core
  - Residence
  - Vault
  - WorldEdit
  - Towny
  - Jobs
  - GriefPrevention
  - PlaceholderAPI
  - WorldGuard
  - Nexo
  - ItemsAdder
  - Oraxen
  - MythicMobs
  - MMOItems
api-version: "1.13"
commands:
  blockregen:
    aliases: [ br, bregen, blockr, breg, brg ]
    description: Main plugin command.

permissions:
  blockregen.admin:
    description: Gives access to admin commands.
    default: op
    children:
      blockregen.tools: true
      blockregen.debug: true
      blockregen.bypass: true
      blockregen.check: true
      blockregen.select: true
      blockregen.region: true
      blockregen.regen: true
      blockregen.events: true
      blockregen.discord: true
      blockregen.stats: true

  blockregen.tools:
    description: Allows player to get selection tools.
  blockregen.debug:
    description: Allows player to turn on debug.
  blockregen.bypass:
    description: Allows player to use the bypass.
  blockregen.check:
    description: Allows player to use the block check.
  blockregen.select:
    description: Allows player to select locations for regions.
  blockregen.region:
    description: Allows player to select presets for regions.
  blockregen.regen:
    description: Allows player to regenerate running processes.
  blockregen.events:
    description: Allows access to event commands.
  blockregen.stats:
    description: Allows view of regeneration statistics.
  blockregen.discord:
    description: Allows view of the discord link.

  blockregen.region.*:
    default: true
    description: Allows player to mine in all regions.
  blockregen.preset.*:
    default: true
    description: Allows player to mine all presets.
  blockregen.block.*:
    default: true
    description: Allows player to mine all blocks.